main: net.silverstonemc.entityclearer.EntityClearer
name: EntityClearer
description: Remove entities from your worlds!
version: %VERSION%
author: JasonHorkles
website: https://github.com/SilverstoneMC/EntityClearer
api-version: '1.20.5'
softdepend:
  - MythicMobs
  - PlaceholderAPI

commands:
  entityclearer:
    aliases: [ ecl ]
    description: "Main command for the EntityClearer plugin"
    permission: entityclearer.basecommand
    usage: "§cUsage: /entityclearer <debug | reload | clearnow>"

permissions:
  entityclearer.basecommand:
    default: op
    description: Base command for the EntityClearer plugin (does nothing by itself)
  entityclearer.clear:
    default: op
    description: Force clear the entities
  entityclearer.debug:
    default: op
    description: Create debug dump
  entityclearer.lowtps:
    default: op
    description: Notification when the TPS is low before the clear task runs
  entityclearer.notify:
    default: op
    description: Notifications when there are problems within the plugin
  entityclearer.reload:
    default: op
    description: Reload the plugin
  entityclearer.removalnotifs.actionbar:
    default: true
    description: Actionbar notifications during the entity removal task
  entityclearer.removalnotifs.chat:
    default: true
    description: Chat notifications during the entity removal task
  entityclearer.removalnotifs.sound:
    default: true
    description: Sound during the entity removal task
  entityclearer.updatenotifs:
    default: op
    description: Notifications when there is an update available
